wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711724720.027179
    t:
      1:
      - 1
      - 2
      - 3
      - 30
      - 55
      3:
      - 13
      - 15
      - 23
      4: 3.10.12
      5: 0.15.10
      8:
      - 5
